# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 421614
  start_block: 0
  contracts:
  - name: PiePay
    address:
    - 0xCfa3fAF4cd8Bfc8ba93f87c30C46dAE62B578a2b
    handler: src/EventHandlers.ts
    events:
    - event: ContributionApproved(address indexed executor, uint256 indexed contributionId, address indexed contributor, uint8 unitType, uint256 unitsAwarded)
    - event: ContributionRejected(address indexed executor, uint256 indexed contributionId, address indexed contributor)
    - event: ContributionSubmitted(address indexed executor, uint256 indexed contributionId, uint8 unitType, uint256 unitsRequested, string description)
    - event: ContributorRemoved(address indexed executor, address indexed contributor)
    - event: ContributorWhitelisted(address indexed executor, address indexed contributor)
    - event: ConversionMultipliersUpdated(address indexed executor, uint16 pToDMultiplier, uint16 pToCMultiplier, uint16 dToCMultiplier)
    - event: PayrollFunded(address indexed executor, uint256 amount)
    - event: PayrollManagerUpdated(address indexed executor, address indexed newManager)
    - event: ProjectInitialized(string name, string description, address indexed executor)
    - event: ProjectLeadUpdated(address indexed executor, address indexed newLead)
    - event: TotalUnitsUpdated(uint8 indexed unitType, uint256 newTotal)
    - event: UnitCapacityUpdated(address indexed executor, uint8 indexed unitType, uint256 newCapacity)
    - event: UnitsConverted(address indexed executor, uint8 indexed fromType, uint8 indexed toType, uint256 fromAmount, uint256 toAmount)
    - event: UnitsDistributed(address indexed executor, uint8 indexed unitType, uint256 totalDistributed, uint256 recipientCount)
unordered_multichain_mode: true
